---
- name: Install repository
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ repository }}"

- name: Clean yum cache
  command: "yum clean all"

- name: Install php
  yum:
    name: "{{ item.name }}"
    state: present
    enablerepo: remi,epel
  with_items:
    - "{{ php_packages }}"

- name: Disable service httpd
  systemd:
    name: httpd
    state: stopped
    daemon_reload: yes
    enabled: no

- name: Set extensions
  copy:
    src: amazon-elasticache-cluster-client.so
    dest: /opt/remi/php74/root/usr/lib64/php/modules/
    mode: 0755
  notify: Restart php-fpm

- name: Set php config
  copy:
    src: php.ini
    dest: /etc/opt/remi/{{ php_version }}/php.ini
    mode: 0644
    backup: yes
  notify: Restart php-fpm

- name: Create a symbolic link
  file:
    src: /usr/bin/{{ php_version}}
    dest: /usr/bin/php
    state: link

- name: Set php-fpm config
  template:
    src: www.j2
    dest: /etc/opt/remi/{{ php_version }}/php-fpm.d/www.conf
    owner: root
    mode: 0644
    backup: yes
  notify: Restart php-fpm

- name: Copy logrotate file
  template:
    src: php-fpm.j2
    dest: /etc/logrotate.d/{{ php_version }}-php-fpm
    owner: root
    mode: 0644
    backup: yes

- name: Set permission & owner
  file:
    path: /var/www
    state: directory
    owner: nginx
    group: www
    mode: 02775
    recurse: yes

